import type { Metadata } from "next";
import { Geist, Geist_Mono , Roboto } from "next/font/google";
import "./globals.css";
import { middleware } from "../middleware";

const robotoSans = Geist({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${roboto.variable}   ${robotoSans.variable} antialiased font-[family-name:var(--font-roboto-sans)] `}
      >
        {children}
      </body>
    </html>
  );
}
